"""empty message

Revision ID: 93e69e267691
Revises: aa64dfa6420f
Create Date: 2022-06-04 19:09:41.785498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e69e267691'
down_revision = 'aa64dfa6420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_description',
                  sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column(
        'seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column(
        'website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_description',
                  sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column(
        'seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'created_at')
    op.drop_column('Venue', 'website')
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'created_at')
    # ### end Alembic commands ###
